vote: # 投票设置
  enable: true # 是否启用自动投票
  wait: 1.5 # 一些操作后等待的时间，如进入投票详情页，提交投票。请根据自身网络状况调整，可以偏大但不能太小
  interval: 5 # 检查是否有未参加投票的间隔时间
  radio: 1 # 单选投票选则的选项，最小值为 1。如果大于投票选项数量，改为选择最后一个选项
  checkbox: # 多选投票选则的选项，每个值的最小值为 1。如果大于投票选项数量，改为选择最后一个选项
    - 1
    - 2
signin: #签到设置
  enable: true # 是否启用自动签到
  wait: 5 # 一些操作后等待的时间，如点击打开应用按钮后等待签到窗口加载完成的时间。请根据自身网络状况调整，可以偏大但不能太小
  interval: 10 # 检查是否有未参加签到的间隔时间
log: #日志设置
  level: DEBUG # 日志等级，可以填以下值: NOTSET(不显示日志), DEBUG, INFO, WARNING, ERROR, CRITICAL
  save2file: true # 是否将日志记录到文件中
  path: ./log/{DATE}-log.txt # 日志文件的保存路径，相对路径或绝对路径皆可。{DATE}是日期变量，程序写日志时会将其替换为具体日期，如2022-12-05
